"""
Interactive Export — LLM-guided export customization.

This module enables conversational, LLM-assisted export specification:
- User describes what they want in natural language
- LLM translates that into an ExportSpec
- User reviews and confirms token estimate before exporting
- Non-interactive mode supports --query for scripting

Examples:
    Interactive mode:
        codilay export ./my-project --interactive

    Non-interactive query mode:
        codilay export ./my-project --query "file structure and linkage only"

    Preset mode:
        codilay export ./my-project --preset structure
"""

import json
import os
from typing import Dict, List, Optional, Tuple

from rich.console import Console
from rich.prompt import Confirm, Prompt
from rich.table import Table

from codilay.export_spec import BUILTIN_PRESETS, ExportSpec, get_preset, list_presets
from codilay.llm_client import LLMClient

console = Console()


SYSTEM_PROMPT = """You are an export specification assistant for CodiLay, a codebase documentation tool.

Your job is to help users create customized export specifications for their documentation.

The user will describe what they want to export in natural language. You should:
1. Understand their intent
2. Determine which sections to include/exclude
3. Decide on the level of detail (strip implementation or keep it)
4. Choose appropriate content filters
5. Respond with a JSON ExportSpec

Available section types typically include:
- overview: High-level project overview
- entry-point: Main entry points and startup flow
- routes/api/endpoints: API definitions
- models/schemas: Data models and types
- auth/authentication: Auth-related code
- middleware: Middleware and request processing
- utilities: Helper functions and utilities
- tests: Test files
- config/configuration: Configuration handling

ExportSpec format:
{
  "include_sections": ["section-id-1", "section-id-2"],  // Empty = all sections
  "exclude_sections": ["section-id-3"],  // Takes precedence
  "include_graph": true,  // Include dependency graph
  "include_unresolved": false,  // Include unresolved refs
  "strip_implementation": false,  // Keep only signatures/interfaces
  "keep": ["function signatures", "cross-links", "file paths"],
  "strip": ["function bodies", "code examples"],
  "summary": "Brief description of what this exports",
  "max_tokens": null,  // null = no limit, or integer
  "format": "markdown"  // markdown | xml | json
}

Section patterns:
- Use exact IDs like "overview", "routes", "models"
- Use wildcards like "auth*" to match all auth-related sections
- Empty include_sections means "include everything except excluded"

Common patterns:
1. "Just file structure" → include overview/routes/models, strip implementation, minimal tokens
2. "API surface" → include routes/api/endpoints/models, keep signatures
3. "Auth module with dependencies" → include auth*, graph=true
4. "Onboarding context" → include overview/entry-point/architecture, strip implementation
5. "Dependencies only" → exclude all sections, graph=true

Respond ONLY with valid JSON matching the ExportSpec format. No other text."""


USER_PROMPT_TEMPLATE = """Create an export specification for the following request:

"{user_query}"

Available sections in this project:
{sections_list}

Respond with just the JSON ExportSpec, nothing else."""


def query_llm_for_spec(
    user_query: str,
    available_sections: List[str],
    llm_client: Optional[LLMClient] = None,
) -> ExportSpec:
    """
    Use LLM to translate user's natural language query into an ExportSpec.

    Args:
        user_query: User's description of what they want to export
        available_sections: List of available section IDs in the project
        llm_client: Optional LLMClient instance (creates one if None)

    Returns:
        ExportSpec generated by the LLM

    Raises:
        Exception: If LLM call fails or response is invalid
    """
    if llm_client is None:
        from codilay.config import CodiLayConfig
        from codilay.settings import Settings

        settings = Settings.load()
        config = CodiLayConfig()
        config.llm_provider = settings.default_provider
        config.llm_model = settings.get_effective_model()
        llm_client = LLMClient(config)

    # Format sections list
    sections_str = "\n".join([f"  - {s}" for s in available_sections])

    user_prompt = USER_PROMPT_TEMPLATE.format(
        user_query=user_query,
        sections_list=sections_str,
    )

    # Call LLM
    response = llm_client.call(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        json_mode=True,
    )

    # Parse JSON response
    try:
        # Response is already parsed as dict if json_mode=True
        if isinstance(response, dict) and "answer" in response:
            # Extract from answer field
            spec_dict = response["answer"]
        else:
            spec_dict = response

        # Handle if it's still a string
        if isinstance(spec_dict, str):
            content = spec_dict.strip()
            if content.startswith("```"):
                # Remove markdown code block markers
                lines = content.split("\n")
                content = "\n".join(lines[1:-1] if len(lines) > 2 else lines)
            spec_dict = json.loads(content)

        spec = ExportSpec.from_dict(spec_dict)
        return spec
    except (json.JSONDecodeError, Exception) as e:
        raise Exception(f"Failed to parse LLM response as ExportSpec: {e}\n\nResponse: {response}")


def estimate_tokens(spec: ExportSpec, exporter) -> Tuple[int, int]:
    """
    Estimate token count for an export spec.

    Args:
        spec: ExportSpec to estimate
        exporter: AIExporter instance with loaded state

    Returns:
        Tuple of (estimated_tokens, character_count)
    """
    # Do a trial export without token limit
    trial_spec = ExportSpec(
        include_sections=spec.include_sections,
        exclude_sections=spec.exclude_sections,
        include_graph=spec.include_graph,
        include_unresolved=spec.include_unresolved,
        strip_implementation=spec.strip_implementation,
        keep=spec.keep,
        strip=spec.strip,
        summary=spec.summary,
        max_tokens=None,  # No limit for estimation
        format=spec.format,
    )

    result = exporter.export(spec=trial_spec)
    char_count = len(result)

    # Use the exporter's token estimation
    from codilay.exporter import AIExporter

    est_tokens = int(char_count / AIExporter.CHARS_PER_TOKEN)

    return est_tokens, char_count


def interactive_export_flow(
    output_dir: str,
    llm_client: Optional[LLMClient] = None,
) -> ExportSpec:
    """
    Run interactive export specification flow with user.

    Args:
        output_dir: Path to CodiLay output directory
        llm_client: Optional LLMClient instance

    Returns:
        Final ExportSpec chosen by user
    """
    from codilay.exporter import AIExporter
    from codilay.state import AgentState

    # Load state to get available sections
    state_path = os.path.join(output_dir, ".codilay_state.json")
    if not os.path.exists(state_path):
        raise FileNotFoundError(f"No state found at {state_path}")

    state = AgentState.load(state_path)
    available_sections = list(state.section_index.keys())

    # Load exporter for token estimation
    links_path = os.path.join(output_dir, "links.json")
    closed_wires = []
    open_wires = []
    project_name = ""

    if os.path.exists(links_path):
        with open(links_path, "r", encoding="utf-8") as f:
            links = json.load(f)
        closed_wires = links.get("closed", [])
        open_wires = links.get("open", [])
        project_name = links.get("project", "")

    exporter = AIExporter(
        section_index=state.section_index,
        section_contents=state.section_contents,
        closed_wires=closed_wires,
        open_wires=open_wires,
        project_name=project_name,
    )

    console.print("\n[bold cyan]Interactive Export[/bold cyan]")
    console.print("\nWhat would you like to export?\n")
    console.print("You can describe it in plain language, for example:")
    console.print('  • "just the file structure and how files link to each other"')
    console.print('  • "overview of where everything is stored and the main entry points"')
    console.print('  • "only the auth and payments modules with their dependencies"')
    console.print('  • "a summary an LLM would need to answer questions about the API layer"')
    console.print()

    # Main conversation loop
    while True:
        user_query = Prompt.ask("[bold]>[/bold]", console=console)

        if not user_query.strip():
            continue

        # Check for special commands
        if user_query.lower() in ["exit", "quit", "q"]:
            raise KeyboardInterrupt()

        # Get LLM to generate spec
        console.print("\n[dim]Generating export specification...[/dim]")
        try:
            spec = query_llm_for_spec(user_query, available_sections, llm_client)
        except Exception as e:
            console.print(f"[red]Error: {e}[/red]")
            continue

        # Estimate tokens
        console.print("[dim]Estimating token count...[/dim]")
        est_tokens, char_count = estimate_tokens(spec, exporter)

        # Show what will be included
        console.print(f"\n[bold]Export Plan:[/bold] {spec.summary}")
        console.print(f"[dim]Estimated size: ~{est_tokens:,} tokens ({char_count:,} chars)[/dim]\n")

        if spec.include_sections:
            console.print("[bold]Including sections:[/bold]")
            for s in spec.include_sections:
                console.print(f"  • {s}")
        else:
            console.print("[bold]Including:[/bold] All sections")

        if spec.exclude_sections:
            console.print("\n[bold]Excluding sections:[/bold]")
            for s in spec.exclude_sections:
                console.print(f"  • {s}")

        console.print(f"\n[bold]Settings:[/bold]")
        console.print(f"  • Dependency graph: {'yes' if spec.include_graph else 'no'}")
        console.print(f"  • Implementation details: {'stripped' if spec.strip_implementation else 'included'}")
        console.print(f"  • Format: {spec.format}")

        # Confirm or adjust
        console.print("\n[bold]What would you like to do?[/bold]")
        console.print("  [1] Export this")
        console.print("  [2] Make it smaller (describe how)")
        console.print("  [3] Add more detail (describe what)")
        console.print("  [4] Start over with a different query")
        console.print("  [5] Cancel")

        choice = Prompt.ask("Choice", choices=["1", "2", "3", "4", "5"], default="1")

        if choice == "1":
            return spec
        elif choice == "2":
            adjustment = Prompt.ask("\n[bold]How should I make it smaller?[/bold]")
            user_query = f"{user_query}, but {adjustment}"
        elif choice == "3":
            adjustment = Prompt.ask("\n[bold]What additional detail do you need?[/bold]")
            user_query = f"{user_query}, and also include {adjustment}"
        elif choice == "4":
            console.print()
            continue
        elif choice == "5":
            raise KeyboardInterrupt()


def show_presets(custom_presets: Optional[Dict[str, Dict]] = None) -> None:
    """Display available presets in a table."""
    table = Table(title="Available Export Presets")
    table.add_column("Name", style="cyan")
    table.add_column("Description", style="white")
    table.add_column("Est. Tokens", style="yellow", justify="right")

    for name, spec in BUILTIN_PRESETS.items():
        est = f"~{spec.max_tokens:,}" if spec.max_tokens else "varies"
        table.add_row(name, spec.summary, est)

    if custom_presets:
        for name, data in custom_presets.items():
            summary = data.get("summary", "Custom preset")
            max_tok = data.get("max_tokens")
            est = f"~{max_tok:,}" if max_tok else "varies"
            table.add_row(f"{name} (custom)", summary, est)

    console.print(table)
